# Fill this in on Streamlit Cloud (or locally for testing)
OPENAI_API_KEY = "your-openai-key"
HUBSPOT_API_KEY = "your-hubspot-key"
AIRDNA_API_KEY = "your-airdna-key"

[google]
type = "service_account"
project_id = "your-project"
private_key_id = "xxx"
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = "xxx@project.iam.gserviceaccount.com"
client_id = "xxx"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
